# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

include Makefile-common

.PHONY: configure-aws
configure-aws: ## Configures the hosted cluster to be able to run Portworx
	@$(ANSIBLE_RUN) ansible/playbooks/configure-aws-portworx.yml
