clusterGroup:
  name: primary

  namespaces:
    - vault
    - open-cluster-management
    - portworx
    - boutique
    - external-secrets-operator:
        operatorGroup: true
        targetNamespaces: []
    - external-secrets

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.15
    portworx:
      name: portworx-certified
      namespace: portworx
      source: certified-operators
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      chart: acm
      chartVersion: 0.2.*
    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      argoProject: hub
      chart: openshift-external-secrets
      chartVersion: 0.0.*
    vault:
      name: vault
      namespace: vault
      chart: hashicorp-vault
      chartVersion: 0.1.*
    portworx:
      name: portworx
      namespace: portworx
      path: charts/portworx
      extraValueFiles:
        - /overrides/portworx.yaml
    machine-config:
      name: machine-config
      namespace: portworx
      path: charts/machine-config
    boutique:
      name: boutique
      namespace: boutique
      chart: boutique
      chartVersion: 0.0.*
      extraValueFiles:
        - /overrides/boutique.yaml

  managedClusterGroups:
    secondary-region:
      name: secondary
      acmlabels:
        - name: clusterGroup
          value: secondary
