clusterGroup:
  name: secondary

  namespaces:
    - golang-external-secrets
    - portworx
    - external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    - external-secrets

  subscriptions:
    portworx:
      name: portworx-certified
      namespace: portworx
      source: certified-operators
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1

  applications:
    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      argoProject: hub
      chart: openshift-external-secrets
      chartVersion: 0.0.*
    machine-config:
      name: machine-config
      namespace: portworx
      path: charts/machine-config
    portworx:
      name: portworx
      namespace: portworx
      path: charts/portworx
      extraValueFiles:
        - /overrides/portworx.yaml
