clusterGroup:
  name: secondary

  namespaces:
    - portworx
    - external-secrets-operator:
        operatorGroup: true
        targetNamespaces: []
    - external-secrets

  subscriptions:
    portworx:
      name: portworx-certified
      namespace: portworx
      source: certified-operators
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1

  applications:
    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      chart: openshift-external-secrets
      chartVersion: 0.0.*
    portworx:
      name: portworx
      namespace: portworx
      path: charts/portworx
      extraValueFiles:
        - /overrides/portworx.yaml
