{{- $clusterPlatform := $.Values.global.clusterPlatform }}
{{- $usePureFlashArray := .Values.usePureFlashArray | default false }}
{{- $usePureStorage := (or $usePureFlashArray .Values.usePureFlashBlade) | default false }}
{{- $usePureStorage := (or .Values.usePureFlashArray .Values.usePureFlashBlade) | default false }}
{{/*
  storagePlatform will follow clusterPlatform unless one (or both) of Pure FlashArray
  or Pure FlashBlade are configured for use, those are treated as a "cloud platform"
  in Portworx and not a standard DAS/SAN bare metal configuration.
*/}}
{{- $storagePlatform := ternary "pure" ($.Values.global.clusterPlatform | lower) $usePureStorage }}
{{- $storageDefaults := mustMergeOverwrite dict .Values.storageDefaults.common (get .Values.storageDefaults $storagePlatform) }}
{{- $storage := mustMergeOverwrite $storageDefaults .Values.storage }}
{{- $usefileSystemDrive := $storage.usefileSystemDrive | default false }}
{{- $devices := compact (ternary $storage.devices (list $storage.devices) (eq (kindOf $storage.devices) "slice")) }}
{{- $usedrivesAndPartitions := $storage.usedrivesAndPartitions | default false }}
{{- $initialStorageNodes := int64 $storage.initialStorageNodes | default 0 }}
{{- $dataInterface := .Values.dataInterface | default "none" }}
{{- $managementInterface := .Values.managementInterface | default "none" }}
{{- $registrySecret := .Values.registrySecret | default "none" }}
{{- $namespace := .Values.namespace | default "portworx" }}
{{- $serviceAccount := .Values.serviceAccount | default "none" }}
{{- $customRegistryURL := .Values.customRegistryURL | default "none" }}
{{- $deleteStrategy := .Values.deleteStrategy | default "none" }}
{{- $deleteStrategyIgnoreVolumes := .Values.deleteStrategyIgnoreVolumes | default false }}
{{- $internalKVDB := .Values.internalKVDB | default true }}
{{- $kvdbDevice := $storage.kvdbDevice | default "none" }}
{{- $journalDevice := $storage.journalDevice | default "auto" }}
{{- $runOnControlPlane := .Values.runOnControlPlane | default false }}
{{- $systemMetadataDevice := $storage.systemMetadataDevice | default "none" }}
{{- $runtimeOptions := .Values.runtimeOptions | default (dict "default-io-profile" "6") }}
{{- $cloudStorageProvider := $storage.cloudProvider | default $storagePlatform }}
{{- $preflightCheck := .Values.preflightCheck | default true }}
{{- $pureFlashArrayType := .Values.pureFlashArray.type | default "ISCSI" | upper }}
{{- if not (or (eq $storagePlatform "baremetal") $devices) }}
{{- fail "Device spec must be supplied in 'devices' when using cloud storage" }}
{{- end }}
{{- if and $storage.enablePxStoreV2 (eq $systemMetadataDevice "none") }}
{{- fail "systemMetadataDevice must be supplied when using PxStore-V2" }}
{{- end }}

apiVersion: core.libopenstorage.org/v1
kind: StorageCluster
metadata:
  name: {{ template "px.clusterName" . }}
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    {{- if eq $.Values.global.clusterPlatform "AWS" }}
    portworx.io/is-eks: "true"
    {{- end }}
    {{- if eq $.Values.global.clusterPlatform "Azure" }}
    portworx.io/is-aks: "true"
    {{- end }}
    portworx.io/is-openshift: "true"
    portworx.com/install-source: helm-rhmcgo
    portworx.com/helm-vars: 'chart="{{.Chart.Name}}-{{.Chart.Version}}"{{range $k, $v := .Values }}{{if and ($v) (ne "clusterGroup" $k) }},{{ $k }}="{{ $v }}" {{end}}{{end}}'
    portworx.io/service-type: "LoadBalancer"
    {{- if $storage.enablePxStoreV2 }}
    portworx.io/misc-args: " -T px-storev2 "
    portworx.io/preflight-check: {{ $preflightCheck | quote }}
    {{- end }}
    {{- if $runOnControlPlane }}
    portworx.io/run-on-master: "true"
    {{- end }}
spec:
  {{- if not (eq $deleteStrategy "none") }}
  deleteStrategy:
    type: {{ $deleteStrategy }}
    ignoreVolumes: {{ $deleteStrategyIgnoreVolumes }}
  {{- end }}
  env:
    {{- if eq $.Values.global.clusterPlatform "Azure" }}
    - name: AZURE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: px-azure
          key: AZURE_CLIENT_SECRET
    - name: AZURE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: px-azure
          key: AZURE_CLIENT_ID
    - name: AZURE_TENANT_ID
      valueFrom:
        secretKeyRef:
          name: px-azure
          key: AZURE_TENANT_ID
    {{- end }}
    {{- if not (eq $serviceAccount "none") }}
    - name: PX_SERVICE_ACCOUNT
      value: {{ $serviceAccount }}
    {{- end }}
    {{- if eq $storagePlatform "pure" }}
    {{- if $usePureFlashArray }}
    - name: PURE_FLASHARRAY_SAN_TYPE
      value: {{ $pureFlashArrayType | quote }}
    {{- if and (eq $pureFlashArrayType "ISCSI") .Values.pureFlashArray.allowedCIDRs }}
    - name: PURE_ISCSI_ALLOWED_CIDRS
      value: {{ join "," .Values.pureFlashArray.allowedCIDRs | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
  image: {{ include "px.getOCIImage" .}}
  imagePullPolicy: Always
  {{- if not (eq $registrySecret "none") }}
  imagePullSecret: {{ $registrySecret }}
  {{- end }}
  {{- if not (eq $customRegistryURL "none") }}
  customImageRegistry: {{ $customRegistryURL }}
  {{- end }}
  kvdb:
    internal: true
  {{- if eq $storagePlatform "baremetal" }}
  storage:
    useAllWithPartitions: {{ $usedrivesAndPartitions }}
    forceUseDisks: {{ $usefileSystemDrive }}
    {{- if $devices }}
    devices:
    {{- range $index, $device := $devices }}
    - {{ $device }}
    {{- end }}
    {{- end }}
    journalDevice: {{ $journalDevice }}
    {{- if and $internalKVDB (ne $kvdbDevice "none") }}
    kvdbDevice: {{ $kvdbDevice }}
    {{- end }}
    {{- if (ne $systemMetadataDevice "none") }}
    systemMetadataDevice: {{ $systemMetadataDevice | quote }}
    {{- end }}
  {{- else }}
  cloudStorage:
    deviceSpecs:
    {{- range $index, $device := $devices }}
    - {{ $device | quote }}
    {{- end }}
    journalDeviceSpec: {{ $journalDevice | quote }}
    {{- if and $internalKVDB (ne $kvdbDevice "none") }}
    kvdbDeviceSpec: {{ $kvdbDevice | quote }}
    {{- end }}
    {{- if (ne $systemMetadataDevice "none") }}
    systemMetadataDeviceSpec: {{ $systemMetadataDevice | quote }}
    {{- end }}
    {{- if (ne $cloudStorageProvider "none") }}
    provider: {{ $cloudStorageProvider | quote }}
    {{- end }}
    {{- if ge $initialStorageNodes 3 }}
    initialStorageNodes: {{ $initialStorageNodes }}
    {{- end }}
  {{- end }}
  {{- if ne .Values.secretType "k8s" }}
  secretsProvider: {{ .Values.secretType }}
  {{- end }}
  {{- if or (ne $dataInterface "none") (ne $managementInterface "none") }}
  network:
    {{- if ne $dataInterface "none" }}
    dataInterface: {{ .Values.network.dataInterface }}
    {{- end }}
    {{- if ne $managementInterface "none" }}
    mgmtInterface: {{ .Values.network.managementInterface }}
    {{- end }}
  {{- end }}
  stork:
    enabled: true
    args:
      webhook-controller: "true"
      admin-namespace: {{ $namespace }}
  {{- if $runtimeOptions }}
  runtimeOptions:
    {{- range $option, $value := $runtimeOptions }}
    {{ $option }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  autopilot:
    enabled: true
  csi:
    enabled: {{ .Values.csi  | default "true" }}
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      exportMetrics: true
