{{- if and (or .Values.usePureFlashArray .Values.usePureFlashBlade) .Values.pureSecretKey .Values.secretStore }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: px-pure-secret
  namespace: portworx
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ required "secretStore.name must be defined" .Values.secretStore.name }}
    kind: {{ required "secretStore.kind must be defined" .Values.secretStore.kind }}
  target:
    name: px-pure-secret
  dataFrom:
    - extract:
        key: {{ .Values.pureSecretKey }}
{{- end }}
