apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio
    template:
      type: Opaque
      engineVersion: v2
      data:
        user: {{ printf "{{ .user }}" | quote }}
        password: {{ printf "{{ .password }}" | quote }}
        host: minio
        port: "9000"
  data:
  - secretKey: user
    remoteRef:
      key: secret/data/global/aws-creds
      property: aws_access_key_id
  - secretKey: password
    remoteRef:
      key: secret/data/global/aws-creds
      property: aws_secret_access_key
