global:
  clusterPlatform: AWS
  clusterDomain: cluster-name.example.com

namespace: portworx              # Recommended namespace for install is 'portworx', change to desired namespace if default is unacceptable
pxnamespace: portworx              # Recommended namespace for install is 'portworx', change to desired namespace if default is unacceptable

secrets:
  useExternalSecrets: false      # Set to true for the aws-cred secret to be created by external secrets (use this in a validated pattern)
  AWSsecretName: aws-creds
  AWSsecretNamespace: kube-system

# Just enough to allow an install with default values. 'common' contains overall defaults
# and then storage defaults per storage platform. The storage platform is the cluster
storageDefaults:
  common:
    enablePxStoreV2: true
  baremetal:
    enablePxStoreV2: false
    usefileSystemDrive: false
    usedrivesAndPartitions: false
  pure:
    devices: "size=100"
    kvdbDevice: "none"
    systemMetadataDevice: "size=64"
  aws:
    devices: "type=gp3,size=20"
    kvdbDevice: "type=gp3,size=150"
    systemMetadataDevice: "type=gp3,size=64"

storage: {}

runOnControlPlane: false

usePureFlashArray: false
usePureFlashBlade: false

pureFlashArray:
  type: iSCSI

network:
  dataInterface: none               # Name of the interface <ethX>
  managementInterface: none         # Name of the interface <ethX>

secretType: k8s                     # Defaults to k8s, but can be aws-kms/k8s/none

csi: true                          # Enable CSI

internalKVDB: true                  # internal KVDB

customRegistryURL:
registrySecret:

serviceAccount:

deleteStrategy: UninstallAndWipe    # Options are Uninstall, UninstallAndWipe, and UninstallAndDelete

# You can determine the correct versions at the following URL: https://install.portworx.com/$PXVER/version?kbver=$KBVER
versions:
  ociMon: "3.6.0" # This will be the "version" string

installParted: true # Standard RHCOS ISOs are missing the parted utility, required by Portworx. Setting this to true creates a machine config to add parted to the nodes
